apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: n2fn
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: docker.io/shiron228/n2fn
