---
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
# knative serving
- name: apply serving-crds
  k8s:
    src: https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-crds.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
- name: apply serving-core
  k8s: 
    src: https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-core.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
- name: apply kourier
  k8s:
    src: https://github.com/knative/net-kourier/releases/download/knative-v1.11.1/kourier.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"

# - name: knative serving, patch
#   k8s:
#     kind: configmap/config-network
#     namespace: knative-serving
#     merge_type: merge
#     state: patched
#     patch:
#     - op: 
#       path: ./patch.json
#   become: true
#   become_user: "{{ ansible_user }}"
# 後でモジュールを使った方法にする
- name: patch configmap/config-network
  command: kubectl patch configmap/config-network -n knative-serving --type merge --patch '{"data":{"ingress-class":"kourier.ingress.networking.knative.dev"}}'
  become: true
  become_user: "{{ ansible_user }}"

- name: apply serving-default-domain
  k8s:
    src: https://github.com/knative/serving/releases/download/knative-v1.11.0/serving-default-domain.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"

# - name: minikube tunnel
#   shell: nohup minikube tunnel &
#   become: true
#   become_user: "{{ ansible_user }}"

# knative eventing
- name: apply eventing-crds
  k8s:
    src: https://github.com/knative/eventing/releases/download/knative-v1.11.1/eventing-crds.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
- name: apply eventing-core
  k8s:
    src: https://github.com/knative/eventing/releases/download/knative-v1.11.1/eventing-core.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"

# RabbitMQ source
- name: apply cluster-operator
  k8s:
    src: https://github.com/rabbitmq/cluster-operator/releases/download/v2.1.0/cluster-operator.yml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
# install cert-manager
- name: apply cert-manager
  k8s:
    # src: https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
    src: https://github.com/cert-manager/cert-manager/releases/download/v1.5.4/cert-manager.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
# ここダサい
- name: sleep 80s
  pause:
    seconds: 80
- name: apply messaging-topology-operator-with-certmanager
  k8s:
    src: https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.10.0/messaging-topology-operator-with-certmanager.yaml
    apply: yes
    # wait: yes
    # wait_sleep: 5
  become: true
  become_user: "{{ ansible_user }}"
- name: apply rabbitmq-source
  k8s:
    src: https://github.com/knative-sandbox/eventing-rabbitmq/releases/download/knative-v1.11.3/rabbitmq-source.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
- name: apply rabbitmq-broker
  k8s:
    src: https://github.com/knative-sandbox/eventing-rabbitmq/releases/download/knative-v1.11.3/rabbitmq-broker.yaml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"
# - name: apply rabbit-auth
#   k8s:
#     src: /home/{{ ansible_user }}/knative-source/rabbitmq/auth.yml
#     apply: yes
#   become: true
#   become_user: "{{ ansible_user }}"

- name: sleep 10s
  pause:
    seconds: 10
- name: apply rabbitmqCluster.yml
  k8s:
    src: /home/{{ ansible_user }}/knative-source/rabbitmq/broker/rabbitmqCluster.yml
    apply: yes
  become: true
  become_user: "{{ ansible_user }}"

# k8sモジュールが何故か使えないのでcommnadモジュールを使っている
- name: apply https://github.com/knative/eventing/releases/download/knative-v1.11.1/in-memory-channel.yaml
  command: "kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.11.1/in-memory-channel.yaml"
  become: true
  become_user: "{{ ansible_user }}"
