---
- name: apt install package
  apt:
    name: 
    - docker.io
    - pipx
    - python3-kubernetes 
- name: add docker group
  user:
    name: "{{ ansible_user }}"
    state: present
    groups:
    - docker
    append: yes

- name: snap install package
  snap:
    name: kubectl
    classic: yes

- name: install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    owner: root
    group: root
    mode: "755"
  
# minikubeの構築
- name: delete minikube
  command: minikube delete
- name: set memory
  command: minikube config set memory 10000
- name: set vcpus
  command: minikube config set cpus 4
- name: start minikube
  command: minikube start --kubernetes-version=v1.26.3
  become: true
  become_user: "{{ ansible_user }}"
